In [31]:
import pandas as pd
import numpy as np

national = pd.read_excel(r"C:\Users\admin\Desktop\BLS Project\raw\OEWS_National_2025\national_M2025_dl.xlsx")
national.shape

(1401, 32)

In [3]:
national.head()

,AREA,AREA_TITLE,AREA_TYPE,PRIM_STATE,NAICS,NAICS_TITLE,I_GROUP,OWN_CODE,OCC_CODE,OCC_TITLE,...,H_MEDIAN,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,ANNUAL,HOURLY
0,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,00-0000,All Occupations,...,24.51,38.71,61.81,31200,37590,50980,80520,128560,NaN,NaN
1,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,11-0000,Management Occupations,...,60.83,84.75,123.71,60130,82970,126520,176280,257310,NaN,NaN
2,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,11-1000,Top Executives,...,52.17,82.85,134.48,50480,73260,108510,172330,279710,NaN,NaN
3,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,11-1010,Chief Executives,...,102.88,171.25,244.1,75700,129540,213990,356200,507730,NaN,NaN
4,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,11-1011,Chief Executives,...,102.88,171.25,244.1,75700,129540,213990,356200,507730,NaN,NaN

In [4]:
national.tail()

,AREA,AREA_TITLE,AREA_TYPE,PRIM_STATE,NAICS,NAICS_TITLE,I_GROUP,OWN_CODE,OCC_CODE,OCC_TITLE,...,H_MEDIAN,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,ANNUAL,HOURLY
1396,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,53-7081,Refuse and Recyclable Material Collectors,...,23.89,29.82,36.49,33590,39080,49690,62020,75900,NaN,NaN
1397,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,53-7120,"Tank Car, Truck, and Ship Loaders",...,28.3,33.69,39.98,39460,46300,58870,70060,83160,NaN,NaN
1398,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,53-7121,"Tank Car, Truck, and Ship Loaders",...,28.3,33.69,39.98,39460,46300,58870,70060,83160,NaN,NaN
1399,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,53-7190,Miscellaneous Material Moving Workers,...,20.1,24.14,30.2,34330,36600,41800,50220,62820,NaN,NaN
1400,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,53-7199,"Material Moving Workers, All Other",...,20.1,24.14,30.2,34330,36600,41800,50220,62820,NaN,NaN

In [5]:
national.columns

Index(['AREA', 'AREA_TITLE', 'AREA_TYPE', 'PRIM_STATE', 'NAICS', 'NAICS_TITLE',
       'I_GROUP', 'OWN_CODE', 'OCC_CODE', 'OCC_TITLE', 'O_GROUP', 'TOT_EMP',
       'EMP_PRSE', 'JOBS_1000', 'LOC_QUOTIENT', 'PCT_TOTAL', 'PCT_RPT',
       'H_MEAN', 'A_MEAN', 'MEAN_PRSE', 'H_PCT10', 'H_PCT25', 'H_MEDIAN',
       'H_PCT75', 'H_PCT90', 'A_PCT10', 'A_PCT25', 'A_MEDIAN', 'A_PCT75',
       'A_PCT90', 'ANNUAL', 'HOURLY'],
      dtype='object')

In [6]:
national.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1401 entries, 0 to 1400
Data columns (total 32 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   AREA          1401 non-null   int64
 1   AREA_TITLE    1401 non-null   object
 2   AREA_TYPE     1401 non-null   int64
 3   PRIM_STATE    1401 non-null   object
 4   NAICS         1401 non-null   int64
 5   NAICS_TITLE   1401 non-null   object
 6   I_GROUP       1401 non-null   object
 7   OWN_CODE      1401 non-null   int64
 8   OCC_CODE      1401 non-null   object
 9   OCC_TITLE     1401 non-null   object
 10  O_GROUP       1401 non-null   object
 11  TOT_EMP       1401 non-null   int64
 12  EMP_PRSE      1401 non-null   float64
 13  JOBS_1000     0 non-null      float64
 14  LOC_QUOTIENT  0 non-null      float64
 15  PCT_TOTAL     0 non-null      float64
 16  PCT_RPT       0 non-null      float64
 17  H_MEAN        1401 non-null   object
 18  A_MEAN        1401 non-null   object
 19  MEAN_PRSE     1401 non-null   float64
 20  H_PCT10       1401 non-null   object
 21  H_PCT25       1401 non-null   object
 22  H_MEDIAN      1401 non-null   object
 23  H_PCT75       1401 non-null   object
 24  H_PCT90       1401 non-null   object
 25  A_PCT10       1401 non-null   object
 26  A_PCT25       1401 non-null   object
 27  A_MEDIAN      1401 non-null   object
 28  A_PCT75       1401 non-null   object
 29  A_PCT90       1401 non-null   object
 30  ANNUAL        81 non-null     object
 31  HOURLY        7 non-null      object
dtypes: float64(6), int64(5), object(21)
memory usage: 350.4+ KB

In [8]:
national.isnull().sum()

AREA               0
AREA_TITLE         0
AREA_TYPE          0
PRIM_STATE         0
NAICS              0
NAICS_TITLE        0
I_GROUP            0
OWN_CODE           0
OCC_CODE           0
OCC_TITLE          0
O_GROUP            0
TOT_EMP            0
EMP_PRSE           0
JOBS_1000       1401
LOC_QUOTIENT    1401
PCT_TOTAL       1401
PCT_RPT         1401
H_MEAN             0
A_MEAN             0
MEAN_PRSE          0
H_PCT10            0
H_PCT25            0
H_MEDIAN           0
H_PCT75            0
H_PCT90            0
A_PCT10            0
A_PCT25            0
A_MEDIAN           0
A_PCT75            0
A_PCT90            0
ANNUAL          1320
HOURLY          1394
dtype: int64

In [9]:
national.duplicated().sum()

np.int64(0)

In [10]:
national.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
AREA,1401.0,NaN,NaN,NaN,99.0,0.0,99.0,99.0,99.0,99.0,99.0
AREA_TITLE,1401,1,U.S.,1401,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AREA_TYPE,1401.0,NaN,NaN,NaN,1.0,0.0,1.0,1.0,1.0,1.0,1.0
PRIM_STATE,1401,1,US,1401,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NAICS,1401.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
NAICS_TITLE,1401,1,Cross-industry,1401,NaN,NaN,NaN,NaN,NaN,NaN,NaN
I_GROUP,1401,1,cross-industry,1401,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OWN_CODE,1401.0,NaN,NaN,NaN,1235.0,0.0,1235.0,1235.0,1235.0,1235.0,1235.0
OCC_CODE,1401,1394,29-2010,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OCC_TITLE,1401,1137,Tour and Travel Guides,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
O_GROUP,1401,5,detailed,830,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TOT_EMP,1401.0,NaN,NaN,NaN,554924.932191,4342790.707563,220.0,20430.0,69990.0,283380.0,155495730.0
EMP_PRSE,1401.0,NaN,NaN,NaN,2.954318,3.569802,0.0,0.9,1.8,3.6,35.0
JOBS_1000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LOC_QUOTIENT,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PCT_TOTAL,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PCT_RPT,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
H_MEAN,1401,905,*,81,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A_MEAN,1401,1028,*,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MEAN_PRSE,1401.0,NaN,NaN,NaN,1.10828,1.47156,0.0,0.4,0.6,1.2,15.9
H_PCT10,1401,777,*,81,NaN,NaN,NaN,NaN,NaN,NaN,NaN
H_PCT25,1401,828,*,81,NaN,NaN,NaN,NaN,NaN,NaN,NaN
H_MEDIAN,1401,878,*,81,NaN,NaN,NaN,NaN,NaN,NaN,NaN
H_PCT75,1401,902,*,81,NaN,NaN,NaN,NaN,NaN,NaN,NaN
H_PCT90,1401,951,*,81,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A_PCT10,1401.0,947.0,31200.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A_PCT25,1401.0,972.0,34320.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A_MEDIAN,1401,1015,*,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A_PCT75,1401,1021,*,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A_PCT90,1401,1059,*,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ANNUAL,81,1,True,81,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HOURLY,7,1,True,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
national["O_GROUP"].value_counts()

O_GROUP
detailed    830
broad       454
minor        94
major        22
total         1
Name: count, dtype: int64

In [17]:
national.groupby("O_GROUP")["OCC_CODE"].nunique().sort_values()

O_GROUP
total         1
major        22
minor        94
broad       454
detailed    830
Name: OCC_CODE, dtype: int64

In [20]:
duplicates = national["OCC_CODE"].duplicated(keep=False)
duplicate_rows = national[duplicates]
duplicate_rows[["OCC_CODE", "OCC_TITLE", "O_GROUP"]]
duplicate_rows[["OCC_CODE", "OCC_TITLE", "O_GROUP"]].sort_values("OCC_CODE")

     OCC_CODE                                          OCC_TITLE   O_GROUP
76    13-1020                       Buyers and Purchasing Agents     broad
77    13-1020                       Buyers and Purchasing Agents  detailed
109   13-2020                  Property Appraisers and Assessors     broad
110   13-2020                  Property Appraisers and Assessors  detailed
571   29-2010  Clinical Laboratory Technologists and Technicians     broad
572   29-2010  Clinical Laboratory Technologists and Technicians  detailed
610   31-1120                Home Health and Personal Care Aides     broad
611   31-1120                Home Health and Personal Care Aides  detailed
777   39-7010                             Tour and Travel Guides     broad
778   39-7010                             Tour and Travel Guides  detailed
1043  47-4090     Miscellaneous Construction and Related Workers     broad
1044  47-4090     Miscellaneous Construction and Related Workers  detailed
1161  51-2090           Miscellaneous Assemblers and Fabricators     broad
1162  51-2090           Miscellaneous Assemblers and Fabricators  detailed

In [4]:
national.apply(lambda col: (col == "*").sum())

AREA             0
AREA_TITLE       0
AREA_TYPE        0
PRIM_STATE       0
NAICS            0
NAICS_TITLE      0
I_GROUP          0
OWN_CODE         0
OCC_CODE         0
OCC_TITLE        0
O_GROUP          0
TOT_EMP          0
EMP_PRSE         0
JOBS_1000        0
LOC_QUOTIENT     0
PCT_TOTAL        0
PCT_RPT          0
H_MEAN          81
A_MEAN           7
MEAN_PRSE        0
H_PCT10         81
H_PCT25         81
H_MEDIAN        81
H_PCT75         81
H_PCT90         81
A_PCT10          7
A_PCT25          7
A_MEDIAN         7
A_PCT75          7
A_PCT90          7
ANNUAL           0
HOURLY           0
dtype: int64

In [13]:
missing_vals = national[national["A_MEDIAN"] == "*"]
missing_vals = missing_vals[["OCC_CODE", "OCC_TITLE", "O_GROUP"]]
missing_vals

    OCC_CODE                                          OCC_TITLE   O_GROUP
463  27-2011                                             Actors  detailed
470  27-2031                                            Dancers  detailed
472  27-2040            Musicians, Singers, and Related Workers     broad
474  27-2042                              Musicians and Singers  detailed
475  27-2090  Miscellaneous Entertainers and Performers, Spo...     broad
476  27-2091                         Disc Jockeys, Except Radio  detailed
477  27-2099  Entertainers and Performers, Sports and Relate...  detailed

In [11]:
missing_hourly = national[national["H_MEDIAN"] == "*"]
missing_annual = national[national["A_MEDIAN"] == "*"]
missing_annual["OCC_CODE"].isin(missing_hourly["OCC_CODE"]).sum()

np.int64(0)

In [12]:
national.dtypes

AREA              int64
AREA_TITLE       object
AREA_TYPE         int64
PRIM_STATE       object
NAICS             int64
NAICS_TITLE      object
I_GROUP          object
OWN_CODE          int64
OCC_CODE         object
OCC_TITLE        object
O_GROUP          object
TOT_EMP           int64
EMP_PRSE        float64
JOBS_1000       float64
LOC_QUOTIENT    float64
PCT_TOTAL       float64
PCT_RPT         float64
H_MEAN           object
A_MEAN           object
MEAN_PRSE       float64
H_PCT10          object
H_PCT25          object
H_MEDIAN         object
H_PCT75          object
H_PCT90          object
A_PCT10          object
A_PCT25          object
A_MEDIAN         object
A_PCT75          object
A_PCT90          object
ANNUAL           object
HOURLY           object
dtype: object

In [4]:
state = pd.read_excel(r"C:\Users\admin\Desktop\BLS Project\raw\OEWS_State_2025\state_M2025_dl.xlsx")
state.shape

(37408, 32)

In [15]:
state.head()

,AREA,AREA_TITLE,AREA_TYPE,PRIM_STATE,NAICS,NAICS_TITLE,I_GROUP,OWN_CODE,OCC_CODE,OCC_TITLE,...,H_MEDIAN,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,ANNUAL,HOURLY
0,1,Alabama,2,AL,0,Cross-industry,cross-industry,1235,00-0000,All Occupations,...,21.96,32.11,48.68,26090,32050,45670,66790,101250,NaN,NaN
1,1,Alabama,2,AL,0,Cross-industry,cross-industry,1235,11-0000,Management Occupations,...,49.99,72.94,100.05,56920,77180,103980,151720,208110,NaN,NaN
2,1,Alabama,2,AL,0,Cross-industry,cross-industry,1235,11-1011,Chief Executives,...,80.01,106.96,152.6,101670,134650,166420,222490,317400,NaN,NaN
3,1,Alabama,2,AL,0,Cross-industry,cross-industry,1235,11-1021,General and Operations Managers,...,53.75,81.5,117.11,55160,76840,111790,169510,243600,NaN,NaN
4,1,Alabama,2,AL,0,Cross-industry,cross-industry,1235,11-2011,Advertising and Promotions Managers,...,31.08,68.85,102.82,60000,62500,64640,143210,213860,NaN,NaN

In [16]:
state.tail()

,AREA,AREA_TITLE,AREA_TYPE,PRIM_STATE,NAICS,NAICS_TITLE,I_GROUP,OWN_CODE,OCC_CODE,OCC_TITLE,...,H_MEDIAN,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,ANNUAL,HOURLY
37403,78,Virgin Islands,3,VI,0,Cross-industry,cross-industry,1235,53-7051,Industrial Truck and Tractor Operators,...,16.94,20.88,25.29,27190,31030,35230,43420,52600,NaN,NaN
37404,78,Virgin Islands,3,VI,0,Cross-industry,cross-industry,1235,53-7061,Cleaners of Vehicles and Equipment,...,13.6,14.99,17.6,22230,26360,28290,31190,36610,NaN,NaN
37405,78,Virgin Islands,3,VI,0,Cross-industry,cross-industry,1235,53-7062,"Laborers and Freight, Stock, and Material Move...",...,15.3,17.99,18.72,26620,28150,31810,37410,38940,NaN,NaN
37406,78,Virgin Islands,3,VI,0,Cross-industry,cross-industry,1235,53-7064,"Packers and Packagers, Hand",...,11,13.08,17.07,21890,21960,22880,27200,35510,NaN,NaN
37407,78,Virgin Islands,3,VI,0,Cross-industry,cross-industry,1235,53-7065,Stockers and Order Fillers,...,13.53,14.18,16.97,23320,25090,28130,29490,35290,NaN,NaN

In [17]:
state.columns

Index(['AREA', 'AREA_TITLE', 'AREA_TYPE', 'PRIM_STATE', 'NAICS', 'NAICS_TITLE',
       'I_GROUP', 'OWN_CODE', 'OCC_CODE', 'OCC_TITLE', 'O_GROUP', 'TOT_EMP',
       'EMP_PRSE', 'JOBS_1000', 'LOC_QUOTIENT', 'PCT_TOTAL', 'PCT_RPT',
       'H_MEAN', 'A_MEAN', 'MEAN_PRSE', 'H_PCT10', 'H_PCT25', 'H_MEDIAN',
       'H_PCT75', 'H_PCT90', 'A_PCT10', 'A_PCT25', 'A_MEDIAN', 'A_PCT75',
       'A_PCT90', 'ANNUAL', 'HOURLY'],
      dtype='object')

In [18]:
state.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37408 entries, 0 to 37407
Data columns (total 32 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   AREA          37408 non-null  int64
 1   AREA_TITLE    37408 non-null  object
 2   AREA_TYPE     37408 non-null  int64
 3   PRIM_STATE    37408 non-null  object
 4   NAICS         37408 non-null  int64
 5   NAICS_TITLE   37408 non-null  object
 6   I_GROUP       37408 non-null  object
 7   OWN_CODE      37408 non-null  int64
 8   OCC_CODE      37408 non-null  object
 9   OCC_TITLE     37408 non-null  object
 10  O_GROUP       37408 non-null  object
 11  TOT_EMP       37408 non-null  object
 12  EMP_PRSE      37408 non-null  object
 13  JOBS_1000     37408 non-null  object
 14  LOC_QUOTIENT  37408 non-null  object
 15  PCT_TOTAL     0 non-null      float64
 16  PCT_RPT       0 non-null      float64
 17  H_MEAN        37408 non-null  object
 18  A_MEAN        37408 non-null  object
 19  MEAN_PRSE     37408 non-null  object
 20  H_PCT10       37408 non-null  object
 21  H_PCT25       37408 non-null  object
 22  H_MEDIAN      37408 non-null  object
 23  H_PCT75       37408 non-null  object
 24  H_PCT90       37408 non-null  object
 25  A_PCT10       37408 non-null  object
 26  A_PCT25       37408 non-null  object
 27  A_MEDIAN      37408 non-null  object
 28  A_PCT75       37408 non-null  object
 29  A_PCT90       37408 non-null  object
 30  ANNUAL        2584 non-null   object
 31  HOURLY        147 non-null    object
dtypes: float64(2), int64(4), object(26)
memory usage: 9.1+ MB

In [19]:
state.isnull().sum()

AREA                0
AREA_TITLE          0
AREA_TYPE           0
PRIM_STATE          0
NAICS               0
NAICS_TITLE         0
I_GROUP             0
OWN_CODE            0
OCC_CODE            0
OCC_TITLE           0
O_GROUP             0
TOT_EMP             0
EMP_PRSE            0
JOBS_1000           0
LOC_QUOTIENT        0
PCT_TOTAL       37408
PCT_RPT         37408
H_MEAN              0
A_MEAN              0
MEAN_PRSE           0
H_PCT10             0
H_PCT25             0
H_MEDIAN            0
H_PCT75             0
H_PCT90             0
A_PCT10             0
A_PCT25             0
A_MEDIAN            0
A_PCT75             0
A_PCT90             0
ANNUAL          34824
HOURLY          37261
dtype: int64

In [22]:
state.duplicated().sum()

np.int64(0)

In [23]:
state.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
AREA,37408.0,NaN,NaN,NaN,30.160661,16.808383,1.0,17.0,30.0,42.0,78.0
AREA_TITLE,37408,54,California,830,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AREA_TYPE,37408.0,NaN,NaN,NaN,2.027053,0.16224,2.0,2.0,2.0,2.0,3.0
PRIM_STATE,37408,54,CA,830,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NAICS,37408.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
NAICS_TITLE,37408,1,Cross-industry,37408,NaN,NaN,NaN,NaN,NaN,NaN,NaN
I_GROUP,37408,1,cross-industry,37408,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OWN_CODE,37408.0,NaN,NaN,NaN,1235.0,0.0,1235.0,1235.0,1235.0,1235.0,1235.0
OCC_CODE,37408,852,00-0000,54,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OCC_TITLE,37408,852,All Occupations,54,NaN,NaN,NaN,NaN,NaN,NaN,NaN
O_GROUP,37408,3,detailed,36168,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TOT_EMP,37408,4010,**,1318,NaN,NaN,NaN,NaN,NaN,NaN,NaN
EMP_PRSE,37408,501,**,1318,NaN,NaN,NaN,NaN,NaN,NaN,NaN
JOBS_1000,37408,7325,**,1318,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LOC_QUOTIENT,37408,848,**,1318,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PCT_TOTAL,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PCT_RPT,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
H_MEAN,37408,6806,*,3054,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A_MEAN,37408,11455,*,625,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MEAN_PRSE,37408.0,292.0,1.1,1047.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
H_PCT10,37408,4399,*,3054,NaN,NaN,NaN,NaN,NaN,NaN,NaN
H_PCT25,37408,5297,*,3054,NaN,NaN,NaN,NaN,NaN,NaN,NaN
H_MEDIAN,37408,6414,*,3054,NaN,NaN,NaN,NaN,NaN,NaN,NaN
H_PCT75,37408,7628,*,3054,NaN,NaN,NaN,NaN,NaN,NaN,NaN
H_PCT90,37408,8975,*,3054,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A_PCT10,37408,7522,*,625,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A_PCT25,37408,8926,*,625,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A_MEDIAN,37408,10654,*,625,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A_PCT75,37408,12571,*,625,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A_PCT90,37408,14533,*,625,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ANNUAL,2584,1,True,2584,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HOURLY,147,1,True,147,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
state["AREA_TITLE"].unique()

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
       'Colorado', 'Connecticut', 'Delaware', 'District of Columbia',
       'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana',
       'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
       'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
       'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
       'New Jersey', 'New Mexico', 'New York', 'North Carolina',
       'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania',
       'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee',
       'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
       'West Virginia', 'Wisconsin', 'Wyoming', 'Guam', 'Puerto Rico',
       'Virgin Islands'], dtype=object)

In [28]:
state["O_GROUP"].value_counts()

O_GROUP
detailed    36168
major        1186
total          54
Name: count, dtype: int64

In [29]:
state[state["TOT_EMP"] == "**"]["OCC_TITLE"].value_counts()

OCC_TITLE
Insurance Appraisers, Auto Damage                                                        14
Floor Sanders and Finishers                                                              13
Dermatologists                                                                           13
Radiologists                                                                             12
Orthodontists                                                                            12
                                                                                         ..
Electro-Mechanical and Mechatronics Technologists and Technicians                         1
Sales Representatives, Wholesale and Manufacturing, Technical and Scientific Products     1
Food Service Managers                                                                     1
Court Reporters and Simultaneous Captioners                                               1
Food Servers, Nonrestaurant                                                               1
Name: count, Length: 474, dtype: int64

In [30]:
state[state["A_MEDIAN"] == "#"]["OCC_TITLE"].value_counts()

OCC_TITLE
Emergency Medicine Physicians            15
Anesthesiologists                        13
Cardiologists                            13
Surgeons, All Other                      11
Orthopedic Surgeons, Except Pediatric     7
Oral and Maxillofacial Surgeons           6
Radiologists                              5
Neurologists                              5
Dermatologists                            5
Obstetricians and Gynecologists           4
Orthodontists                             3
Physicians, Pathologists                  2
General Internal Medicine Physicians      1
Physicians, All Other                     1
Pediatric Surgeons                        1
Name: count, dtype: int64

In [31]:
state[state["A_MEDIAN"] == "~"]["OCC_TITLE"].value_counts()

Series([], Name: count, dtype: int64)

In [6]:
msa = pd.read_excel(r"C:\Users\admin\Desktop\BLS Project\raw\OEWS_Metro_2025\MSA_M2025_dl.xlsx")
msa.shape

(150023, 32)

In [7]:
msa.head()

,AREA,AREA_TITLE,AREA_TYPE,PRIM_STATE,NAICS,NAICS_TITLE,I_GROUP,OWN_CODE,OCC_CODE,OCC_TITLE,...,H_MEDIAN,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,ANNUAL,HOURLY
0,10180,"Abilene, TX",4,TX,0,Cross-industry,cross-industry,1235,00-0000,All Occupations,...,21.32,29.92,45.19,24900,30980,44340,62230,93990,NaN,NaN
1,10180,"Abilene, TX",4,TX,0,Cross-industry,cross-industry,1235,11-0000,Management Occupations,...,45.9,64.34,92.98,47790,64990,95480,133840,193390,NaN,NaN
2,10180,"Abilene, TX",4,TX,0,Cross-industry,cross-industry,1235,11-1011,Chief Executives,...,79.7,113.51,187.68,88400,121980,165770,236100,390370,NaN,NaN
3,10180,"Abilene, TX",4,TX,0,Cross-industry,cross-industry,1235,11-1021,General and Operations Managers,...,41.44,67.13,101.14,43770,57740,86200,139630,210360,NaN,NaN
4,10180,"Abilene, TX",4,TX,0,Cross-industry,cross-industry,1235,11-2021,Marketing Managers,...,52.45,74.4,95.07,71010,85770,109100,154750,197740,NaN,NaN

In [8]:
msa.tail()

,AREA,AREA_TITLE,AREA_TYPE,PRIM_STATE,NAICS,NAICS_TITLE,I_GROUP,OWN_CODE,OCC_CODE,OCC_TITLE,...,H_MEDIAN,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,ANNUAL,HOURLY
150018,49740,"Yuma, AZ",4,AZ,0,Cross-industry,cross-industry,1235,53-7051,Industrial Truck and Tractor Operators,...,18.18,19.32,21.1,33090,35100,37820,40180,43890,NaN,NaN
150019,49740,"Yuma, AZ",4,AZ,0,Cross-industry,cross-industry,1235,53-7061,Cleaners of Vehicles and Equipment,...,15.74,17.62,19.04,30580,30890,32750,36650,39610,NaN,NaN
150020,49740,"Yuma, AZ",4,AZ,0,Cross-industry,cross-industry,1235,53-7062,"Laborers and Freight, Stock, and Material Move...",...,17.11,19.47,22.15,30750,33130,35580,40490,46070,NaN,NaN
150021,49740,"Yuma, AZ",4,AZ,0,Cross-industry,cross-industry,1235,53-7064,"Packers and Packagers, Hand",...,14.7,14.86,15.09,30580,30580,30580,30900,31390,NaN,NaN
150022,49740,"Yuma, AZ",4,AZ,0,Cross-industry,cross-industry,1235,53-7065,Stockers and Order Fillers,...,18.18,19.02,21.97,30750,33570,37810,39570,45700,NaN,NaN

In [10]:
msa.columns

Index(['AREA', 'AREA_TITLE', 'AREA_TYPE', 'PRIM_STATE', 'NAICS', 'NAICS_TITLE',
       'I_GROUP', 'OWN_CODE', 'OCC_CODE', 'OCC_TITLE', 'O_GROUP', 'TOT_EMP',
       'EMP_PRSE', 'JOBS_1000', 'LOC_QUOTIENT', 'PCT_TOTAL', 'PCT_RPT',
       'H_MEAN', 'A_MEAN', 'MEAN_PRSE', 'H_PCT10', 'H_PCT25', 'H_MEDIAN',
       'H_PCT75', 'H_PCT90', 'A_PCT10', 'A_PCT25', 'A_MEDIAN', 'A_PCT75',
       'A_PCT90', 'ANNUAL', 'HOURLY'],
      dtype='object')

In [11]:
msa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150023 entries, 0 to 150022
Data columns (total 32 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   AREA          150023 non-null  int64
 1   AREA_TITLE    150023 non-null  object
 2   AREA_TYPE     150023 non-null  int64
 3   PRIM_STATE    150023 non-null  object
 4   NAICS         150023 non-null  int64
 5   NAICS_TITLE   150023 non-null  object
 6   I_GROUP       150023 non-null  object
 7   OWN_CODE      150023 non-null  int64
 8   OCC_CODE      150023 non-null  object
 9   OCC_TITLE     150023 non-null  object
 10  O_GROUP       150023 non-null  object
 11  TOT_EMP       150023 non-null  object
 12  EMP_PRSE      150023 non-null  object
 13  JOBS_1000     150023 non-null  object
 14  LOC_QUOTIENT  150023 non-null  object
 15  PCT_TOTAL     0 non-null       float64
 16  PCT_RPT       0 non-null       float64
 17  H_MEAN        150023 non-null  object
 18  A_MEAN        150023 non-null  object
 19  MEAN_PRSE     150023 non-null  object
 20  H_PCT10       150023 non-null  object
 21  H_PCT25       150023 non-null  object
 22  H_MEDIAN      150023 non-null  object
 23  H_PCT75       150023 non-null  object
 24  H_PCT90       150023 non-null  object
 25  A_PCT10       150023 non-null  object
 26  A_PCT25       150023 non-null  object
 27  A_MEDIAN      150023 non-null  object
 28  A_PCT75       150023 non-null  object
 29  A_PCT90       150023 non-null  object
 30  ANNUAL        7847 non-null    object
 31  HOURLY        262 non-null     object
dtypes: float64(2), int64(4), object(26)
memory usage: 36.6+ MB

In [12]:
msa.isnull().sum()

AREA                 0
AREA_TITLE           0
AREA_TYPE            0
PRIM_STATE           0
NAICS                0
NAICS_TITLE          0
I_GROUP              0
OWN_CODE             0
OCC_CODE             0
OCC_TITLE            0
O_GROUP              0
TOT_EMP              0
EMP_PRSE             0
JOBS_1000            0
LOC_QUOTIENT         0
PCT_TOTAL       150023
PCT_RPT         150023
H_MEAN               0
A_MEAN               0
MEAN_PRSE            0
H_PCT10              0
H_PCT25              0
H_MEDIAN             0
H_PCT75              0
H_PCT90              0
A_PCT10              0
A_PCT25              0
A_MEDIAN             0
A_PCT75              0
A_PCT90              0
ANNUAL          142176
HOURLY          149761
dtype: int64

In [14]:
msa.duplicated().sum()

np.int64(0)

In [15]:
msa.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
AREA,150023.0,NaN,NaN,NaN,29997.656959,11463.330104,10180.0,19740.0,29940.0,40140.0,49740.0
AREA_TITLE,150023,393,"New York-Newark-Jersey City, NY-NJ",792,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AREA_TYPE,150023.0,NaN,NaN,NaN,4.0,0.0,4.0,4.0,4.0,4.0,4.0
PRIM_STATE,150023,52,CA,11449,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NAICS,150023.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
NAICS_TITLE,150023,1,Cross-industry,150023,NaN,NaN,NaN,NaN,NaN,NaN,NaN
I_GROUP,150023,1,cross-industry,150023,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OWN_CODE,150023.0,NaN,NaN,NaN,1235.0,0.0,1235.0,1235.0,1235.0,1235.0,1235.0
OCC_CODE,150023,847,00-0000,393,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OCC_TITLE,150023,847,All Occupations,393,NaN,NaN,NaN,NaN,NaN,NaN,NaN
O_GROUP,150023,3,detailed,141015,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TOT_EMP,150023.0,3959.0,40.0,8895.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
EMP_PRSE,150023,501,**,2939,NaN,NaN,NaN,NaN,NaN,NaN,NaN
JOBS_1000,150023,21712,**,2939,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LOC_QUOTIENT,150023,1589,**,2939,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PCT_TOTAL,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PCT_RPT,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
H_MEAN,150023,9425,*,9291,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A_MEAN,150023,16494,*,1714,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MEAN_PRSE,150023.0,299.0,1.1,4232.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
H_PCT10,150023,5805,*,9291,NaN,NaN,NaN,NaN,NaN,NaN,NaN
H_PCT25,150023,7223,*,9291,NaN,NaN,NaN,NaN,NaN,NaN,NaN
H_MEDIAN,150023,8856,*,9291,NaN,NaN,NaN,NaN,NaN,NaN,NaN
H_PCT75,150023,10765,*,9291,NaN,NaN,NaN,NaN,NaN,NaN,NaN
H_PCT90,150023,13347,*,9291,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A_PCT10,150023,10420,*,1714,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A_PCT25,150023,12708,*,1714,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A_MEDIAN,150023,15395,*,1714,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A_PCT75,150023,18790,*,1714,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A_PCT90,150023,22886,*,1714,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ANNUAL,7847,1,True,7847,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HOURLY,262,1,True,262,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
msa["AREA_TITLE"].value_counts().head(10)

AREA_TITLE
New York-Newark-Jersey City, NY-NJ              792
Los Angeles-Long Beach-Anaheim, CA              777
Philadelphia-Camden-Wilmington, PA-NJ-DE-MD     757
Dallas-Fort Worth-Arlington, TX                 749
Chicago-Naperville-Elgin, IL-IN                 749
Washington-Arlington-Alexandria, DC-VA-MD-WV    736
Houston-Pasadena-The Woodlands, TX              731
Boston-Cambridge-Newton, MA-NH                  726
Seattle-Tacoma-Bellevue, WA                     725
San Francisco-Oakland-Fremont, CA               724
Name: count, dtype: int64

In [18]:
msa[msa["TOT_EMP"] == "**"]["OCC_TITLE"].value_counts().head(20)

OCC_TITLE
Real Estate Brokers                                          51
Real Estate Sales Agents                                     39
Tree Trimmers and Pruners                                    34
Cooks, Short Order                                           31
Radiologists                                                 29
Nurse Anesthetists                                           26
Marriage and Family Therapists                               25
General Internal Medicine Physicians                         25
Food Preparation and Serving Related Workers, All Other      23
Family Medicine Physicians                                   21
Anesthesiologists                                            20
Health Specialties Teachers, Postsecondary                   19
Life, Physical, and Social Science Technicians, All Other    17
Surgeons, All Other                                          17
Dermatologists                                               17
Audiovisual Equipment Installers and Repairers               16
Computer Programmers                                         16
Helpers--Carpenters                                          16
Emergency Medicine Physicians                                16
Obstetricians and Gynecologists                              15
Name: count, dtype: int64

In [20]:
msa[msa["H_MEDIAN"] == "*"]["OCC_TITLE"].value_counts().head(20)

OCC_TITLE
Teaching Assistants, Except Postsecondary                                   391
Education Administrators, Kindergarten through Secondary                    387
Elementary School Teachers, Except Special Education                        383
Secondary School Teachers, Except Special and Career/Technical Education    375
Middle School Teachers, Except Special and Career/Technical Education       357
Coaches and Scouts                                                          349
Special Education Teachers, Kindergarten and Elementary School              335
Special Education Teachers, Secondary School                                315
Kindergarten Teachers, Except Special Education                             294
Career/Technical Education Teachers, Secondary School                       247
Teachers and Instructors, All Other                                         246
Special Education Teachers, Middle School                                   242
Health Specialties Teachers, Postsecondary                                  202
Business Teachers, Postsecondary                                            181
Nursing Instructors and Teachers, Postsecondary                             178
Postsecondary Teachers, All Other                                           170
Commercial Pilots                                                           161
Athletic Trainers                                                           161
Mathematical Science Teachers, Postsecondary                                155
Education Teachers, Postsecondary                                           153
Name: count, dtype: int64

In [21]:
msa[msa["A_MEDIAN"] == "#"]["OCC_TITLE"].value_counts().head(20)

OCC_TITLE
Anesthesiologists                        28
Emergency Medicine Physicians            26
Cardiologists                            24
Radiologists                             21
Surgeons, All Other                      17
General Internal Medicine Physicians     17
Orthopedic Surgeons, Except Pediatric    12
Nurse Anesthetists                       11
Obstetricians and Gynecologists          11
Dermatologists                            7
Physicians, All Other                     7
Physicians, Pathologists                  7
Neurologists                              5
Orthodontists                             4
Ophthalmologists, Except Pediatric        3
Psychiatrists                             3
Oral and Maxillofacial Surgeons           3
Pediatric Surgeons                        1
Family Medicine Physicians                1
Name: count, dtype: int64

In [24]:
bos = pd.read_excel(r"C:\Users\admin\Desktop\BLS Project\raw\OEWS_Nonmetro_2025\BOS_M2025_dl.xlsx")
bos.shape

(48689, 32)

In [25]:
bos.head()

,AREA,AREA_TITLE,AREA_TYPE,PRIM_STATE,NAICS,NAICS_TITLE,I_GROUP,OWN_CODE,OCC_CODE,OCC_TITLE,...,H_MEDIAN,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,ANNUAL,HOURLY
0,100001,Northwest Alabama nonmetropolitan area,6,AL,0,Cross-industry,cross-industry,1235,00-0000,All Occupations,...,19.71,26.99,36.87,23570,30750,41000,56130,76700,NaN,NaN
1,100001,Northwest Alabama nonmetropolitan area,6,AL,0,Cross-industry,cross-industry,1235,11-0000,Management Occupations,...,46.11,61.34,84.82,50920,65010,95910,127590,176420,NaN,NaN
2,100001,Northwest Alabama nonmetropolitan area,6,AL,0,Cross-industry,cross-industry,1235,11-1011,Chief Executives,...,72.82,87.54,110.05,123440,128860,151460,182090,228910,NaN,NaN
3,100001,Northwest Alabama nonmetropolitan area,6,AL,0,Cross-industry,cross-industry,1235,11-1021,General and Operations Managers,...,50,75.01,102.7,51990,64780,103990,156020,213610,NaN,NaN
4,100001,Northwest Alabama nonmetropolitan area,6,AL,0,Cross-industry,cross-industry,1235,11-2022,Sales Managers,...,62.39,83.96,104.94,65860,87490,129770,174630,218270,NaN,NaN

In [26]:
bos.tail()

,AREA,AREA_TITLE,AREA_TYPE,PRIM_STATE,NAICS,NAICS_TITLE,I_GROUP,OWN_CODE,OCC_CODE,OCC_TITLE,...,H_MEDIAN,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,ANNUAL,HOURLY
48684,7800001,Virgin Islands,6,VI,0,Cross-industry,cross-industry,1235,53-7051,Industrial Truck and Tractor Operators,...,16.94,20.88,25.29,27190,31030,35230,43420,52600,NaN,NaN
48685,7800001,Virgin Islands,6,VI,0,Cross-industry,cross-industry,1235,53-7061,Cleaners of Vehicles and Equipment,...,13.6,14.99,17.6,22230,26360,28290,31190,36610,NaN,NaN
48686,7800001,Virgin Islands,6,VI,0,Cross-industry,cross-industry,1235,53-7062,"Laborers and Freight, Stock, and Material Move...",...,15.3,17.99,18.72,26620,28150,31810,37410,38940,NaN,NaN
48687,7800001,Virgin Islands,6,VI,0,Cross-industry,cross-industry,1235,53-7064,"Packers and Packagers, Hand",...,11,13.08,17.07,21890,21960,22880,27200,35510,NaN,NaN
48688,7800001,Virgin Islands,6,VI,0,Cross-industry,cross-industry,1235,53-7065,Stockers and Order Fillers,...,13.53,14.18,16.97,23320,25090,28130,29490,35290,NaN,NaN

In [32]:
bos.columns

Index(['AREA', 'AREA_TITLE', 'AREA_TYPE', 'PRIM_STATE', 'NAICS', 'NAICS_TITLE',
       'I_GROUP', 'OWN_CODE', 'OCC_CODE', 'OCC_TITLE', 'O_GROUP', 'TOT_EMP',
       'EMP_PRSE', 'JOBS_1000', 'LOC_QUOTIENT', 'PCT_TOTAL', 'PCT_RPT',
       'H_MEAN', 'A_MEAN', 'MEAN_PRSE', 'H_PCT10', 'H_PCT25', 'H_MEDIAN',
       'H_PCT75', 'H_PCT90', 'A_PCT10', 'A_PCT25', 'A_MEDIAN', 'A_PCT75',
       'A_PCT90', 'ANNUAL', 'HOURLY'],
      dtype='object')

In [33]:
bos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48689 entries, 0 to 48688
Data columns (total 32 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   AREA          48689 non-null  int64
 1   AREA_TITLE    48689 non-null  object
 2   AREA_TYPE     48689 non-null  int64
 3   PRIM_STATE    48689 non-null  object
 4   NAICS         48689 non-null  int64
 5   NAICS_TITLE   48689 non-null  object
 6   I_GROUP       48689 non-null  object
 7   OWN_CODE      48689 non-null  int64
 8   OCC_CODE      48689 non-null  object
 9   OCC_TITLE     48689 non-null  object
 10  O_GROUP       48689 non-null  object
 11  TOT_EMP       48689 non-null  object
 12  EMP_PRSE      48689 non-null  object
 13  JOBS_1000     48689 non-null  object
 14  LOC_QUOTIENT  48689 non-null  object
 15  PCT_TOTAL     0 non-null      float64
 16  PCT_RPT       0 non-null      float64
 17  H_MEAN        48689 non-null  object
 18  A_MEAN        48689 non-null  object
 19  MEAN_PRSE     48689 non-null  object
 20  H_PCT10       48689 non-null  object
 21  H_PCT25       48689 non-null  object
 22  H_MEDIAN      48689 non-null  object
 23  H_PCT75       48689 non-null  object
 24  H_PCT90       48689 non-null  object
 25  A_PCT10       48689 non-null  object
 26  A_PCT25       48689 non-null  object
 27  A_MEDIAN      48689 non-null  object
 28  A_PCT75       48689 non-null  object
 29  A_PCT90       48689 non-null  object
 30  ANNUAL        2544 non-null   object
 31  HOURLY        14 non-null     object
dtypes: float64(2), int64(4), object(26)
memory usage: 11.9+ MB

In [34]:
bos.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
AREA,48689.0,NaN,NaN,NaN,3100792.080799,1581007.619478,100001.0,1900001.0,3000006.0,4500003.0,7800001.0
AREA_TITLE,48689,137,Kansas nonmetropolitan area,512,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AREA_TYPE,48689.0,NaN,NaN,NaN,6.0,0.0,6.0,6.0,6.0,6.0,6.0
PRIM_STATE,48689,51,TX,2256,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NAICS,48689.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
NAICS_TITLE,48689,1,Cross-industry,48689,NaN,NaN,NaN,NaN,NaN,NaN,NaN
I_GROUP,48689,1,cross-industry,48689,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OWN_CODE,48689.0,NaN,NaN,NaN,1235.0,0.0,1235.0,1235.0,1235.0,1235.0,1235.0
OCC_CODE,48689,774,00-0000,137,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OCC_TITLE,48689,774,All Occupations,137,NaN,NaN,NaN,NaN,NaN,NaN,NaN
O_GROUP,48689,3,detailed,45542,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TOT_EMP,48689.0,1436.0,40.0,3712.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
EMP_PRSE,48689,501,**,760,NaN,NaN,NaN,NaN,NaN,NaN,NaN
JOBS_1000,48689,12190,**,760,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LOC_QUOTIENT,48689,1514,**,760,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PCT_TOTAL,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PCT_RPT,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
H_MEAN,48689,6370,*,2952,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A_MEAN,48689,11005,*,435,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MEAN_PRSE,48689.0,273.0,1.6,1293.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
H_PCT10,48689,4215,*,2952,NaN,NaN,NaN,NaN,NaN,NaN,NaN
H_PCT25,48689,5064,*,2952,NaN,NaN,NaN,NaN,NaN,NaN,NaN
H_MEDIAN,48689,5948,*,2952,NaN,NaN,NaN,NaN,NaN,NaN,NaN
H_PCT75,48689,7191,*,2952,NaN,NaN,NaN,NaN,NaN,NaN,NaN
H_PCT90,48689,8662,*,2952,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A_PCT10,48689.0,7351.0,31200.0,631.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A_PCT25,48689,8675,*,435,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A_MEDIAN,48689,10207,*,435,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A_PCT75,48689,12151,*,435,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A_PCT90,48689,14208,*,435,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ANNUAL,2544,1,True,2544,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HOURLY,14,1,True,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
bos[bos["TOT_EMP"] == "**"]["OCC_TITLE"].value_counts()

OCC_TITLE
Real Estate Sales Agents                                       19
Tree Trimmers and Pruners                                      13
Cooks, Short Order                                             13
Insurance Claims and Policy Processing Clerks                  12
Firefighters                                                   10
                                                               ..
Cutting and Slicing Machine Setters, Operators, and Tenders     1
Mechanical Engineering Technologists and Technicians            1
First-Line Supervisors of Personal Service Workers              1
Highway Maintenance Workers                                     1
Landscaping and Groundskeeping Workers                          1
Name: count, Length: 357, dtype: int64

In [36]:
bos[bos["H_MEDIAN"] == "*"]["OCC_TITLE"].value_counts()

OCC_TITLE
Education Administrators, Kindergarten through Secondary                    137
Elementary School Teachers, Except Special Education                        137
Secondary School Teachers, Except Special and Career/Technical Education    137
Teaching Assistants, Except Postsecondary                                   137
Middle School Teachers, Except Special and Career/Technical Education       134
                                                                           ...
Anesthesiologists                                                             1
Occupational Health and Safety Technicians                                    1
Agricultural Technicians                                                      1
Motorcycle Mechanics                                                          1
Industrial Machinery Mechanics                                                1
Name: count, Length: 252, dtype: int64

In [37]:
bos[bos["A_MEDIAN"] == "#"]["OCC_TITLE"].value_counts()

OCC_TITLE
Emergency Medicine Physicians      15
Nurse Anesthetists                  5
Surgeons, All Other                 4
Anesthesiologists                   4
Cardiologists                       4
Physicians, All Other               3
Family Medicine Physicians          2
Pediatricians, General              1
Obstetricians and Gynecologists     1
Name: count, dtype: int64

In [41]:
ep = pd.read_excel(r"C:\Users\admin\Desktop\BLS Project\raw\occupation.xlsx", sheet_name="Table 1.2", header=1)
ep.shape

(1117, 17)

In [42]:
ep.columns

Index(['2025 National Employment Matrix title',
       '2025 National Employment Matrix code', 'Occupation type',
       'Employment, 2025', 'Employment, 2035',
       'Employment distribution, percent, 2025',
       'Employment distribution, percent, 2035',
       'Employment change, numeric, 2025–35',
       'Employment change, percent, 2025–35', 'Percent self-employed, 2025',
       'Occupational openings, 2025–35 annual average',
       'Median annual wage, dollars, 2025',
       'Typical education needed for entry',
       'Work experience in a related occupation',
       'Typical on-the-job training needed to attain competency in the occupation',
       'Related Occupational Outlook Handbook (OOH) content',
       'Related Occupational Outlook Handbook (OOH) content.1'],
      dtype='object')

In [43]:
ep.head()

,2025 National Employment Matrix title,2025 National Employment Matrix code,Occupation type,"Employment, 2025","Employment, 2035","Employment distribution, percent, 2025","Employment distribution, percent, 2035","Employment change, numeric, 2025–35","Employment change, percent, 2025–35","Percent self-employed, 2025","Occupational openings, 2025–35 annual average","Median annual wage, dollars, 2025",Typical education needed for entry,Work experience in a related occupation,Typical on-the-job training needed to attain competency in the occupation,Related Occupational Outlook Handbook (OOH) content,Related Occupational Outlook Handbook (OOH) content.1
0,"Total, all occupations",00-0000,Summary,170280.8,176198.5,100.0,100.0,5917.6,3.5,5.8,17461.8,50980,—,—,—,—,—
1,Management occupations,11-0000,Summary,13683.4,14527.6,8.0,8.2,844.2,6.2,14.4,1081.7,126520,—,—,—,—,—
2,Top executives,11-1000,Summary,3904.1,4095.2,2.3,2.3,191.1,4.9,2.7,305.1,108510,—,—,—,—,—
3,Chief executives,11-1011,Line item,291.6,300.9,0.2,0.2,9.3,3.2,26.6,19.1,213990,Bachelor's degree,5 years or more,NaN,OOH Content,"<a href=""https://www.bls.gov/ooh/management/to..."
4,General and operations managers,11-1021,Line item,3599.0,3780.3,2.1,2.1,181.3,5.0,0.8,285.0,105770,Bachelor's degree,5 years or more,NaN,OOH Content,"<a href=""https://www.bls.gov/ooh/management/to..."

In [44]:
ep.tail()

,2025 National Employment Matrix title,2025 National Employment Matrix code,Occupation type,"Employment, 2025","Employment, 2035","Employment distribution, percent, 2025","Employment distribution, percent, 2035","Employment change, numeric, 2025–35","Employment change, percent, 2025–35","Percent self-employed, 2025","Occupational openings, 2025–35 annual average","Median annual wage, dollars, 2025",Typical education needed for entry,Work experience in a related occupation,Typical on-the-job training needed to attain competency in the occupation,Related Occupational Outlook Handbook (OOH) content,Related Occupational Outlook Handbook (OOH) content.1
1112,Note:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1113,Wage data are from the Occupational Employment...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1114,Data is unavailable for values denoted with a ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1115,Employment subcategories do not necessarily ad...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1116,Source: U.S. Bureau of Labor Statistics.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
openings = pd.read_excel(r"C:\Users\admin\Desktop\BLS Project\raw\occupation.xlsx", sheet_name="Table 1.10", header=1)
openings.shape

(1115, 14)

In [46]:
openings.columns

Index(['2025 National Employment Matrix title',
       '2025 National Employment Matrix code', 'Occupation type',
       'Employment, 2025', 'Employment, 2035',
       'Employment change, numeric, 2025–35',
       'Employment change, percent, 2025–35',
       'Labor force exit rate, 2025–35 annual average',
       'Occupational transfer rate, 2025–35 annual average',
       'Total occupational separations rate, 2025–35 annual average',
       'Labor force exits, 2025–35 annual average',
       'Occupational transfers, 2025–35 annual average',
       'Total occupational separations, 2025–35 annual average',
       'Occupational openings, 2025–35 annual average'],
      dtype='object')

In [47]:
openings.head()

,2025 National Employment Matrix title,2025 National Employment Matrix code,Occupation type,"Employment, 2025","Employment, 2035","Employment change, numeric, 2025–35","Employment change, percent, 2025–35","Labor force exit rate, 2025–35 annual average","Occupational transfer rate, 2025–35 annual average","Total occupational separations rate, 2025–35 annual average","Labor force exits, 2025–35 annual average","Occupational transfers, 2025–35 annual average","Total occupational separations, 2025–35 annual average","Occupational openings, 2025–35 annual average"
0,"Total, all occupations",00-0000,Summary,170280.8,176198.5,5917.6,3.5,4.2,5.5,9.7,7362.4,9507.6,16870.0,17461.8
1,Management occupations,11-0000,Summary,13683.4,14527.6,844.2,6.2,2.5,4.6,7.1,355.4,641.9,997.3,1081.7
2,Top executives,11-1000,Summary,3904.1,4095.2,191.1,4.9,2.1,5.0,7.2,85.9,200.1,286.0,305.1
3,Chief executives,11-1011,Line item,291.6,300.9,9.3,3.2,2.7,3.5,6.1,8.0,10.3,18.2,19.1
4,General and operations managers,11-1021,Line item,3599.0,3780.3,181.3,5.0,2.1,5.1,7.2,77.6,189.2,266.9,285.0

In [48]:
openings.tail()

,2025 National Employment Matrix title,2025 National Employment Matrix code,Occupation type,"Employment, 2025","Employment, 2035","Employment change, numeric, 2025–35","Employment change, percent, 2025–35","Labor force exit rate, 2025–35 annual average","Occupational transfer rate, 2025–35 annual average","Total occupational separations rate, 2025–35 annual average","Labor force exits, 2025–35 annual average","Occupational transfers, 2025–35 annual average","Total occupational separations, 2025–35 annual average","Occupational openings, 2025–35 annual average"
1110,"Tank car, truck, and ship loaders",53-7121,Line item,12.8,13.2,0.4,2.8,3.8,6.0,9.7,0.5,0.8,1.3,1.3
1111,"Material moving workers, all other",53-7199,Line item,27.8,28.6,0.8,2.7,3.8,6.0,9.7,1.1,1.7,2.7,2.8
1112,Note:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1113,Employment subcategories do not necessarily ad...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1114,Source: U.S. Bureau of Labor Statistics.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN